### ISSUE TITLE
Mysterious Button Near Luck Produces Mysterious Chat Messages

### ISSUE THREAD

**Issue by claycle** [HavlockV/CoC7-FoundryVTT#1015]
![](https://user-images.githubusercontent.com/419840/154862414-fa56e6a3-54f2-4063-abda-519506b8e228.png)

### Prerequisites.

There is an odd icon near the luck on the character sheet. Clicking it produces odd messages.

## Description.

<img width="195" alt="image" src="https://user-images.githubusercontent.com/419840/154862635-ad3f5b32-d81b-4cdf-88b8-06dcb67dc6e2.png">

<img width="309" alt="image" src="https://user-images.githubusercontent.com/419840/154862646-bb675c82-bdc2-4abe-8f7a-655bd7929933.png">

**Comment by joaovscorreia** [comment]
Resolved by [67025ad](https://github.com/Miskatonic-Investigative-Society/CoC7-FoundryVTT/commit/67025ade4d9e6aba5ef7fdcc0be0569f92dbbafb). Thanks!
