### ISSUE TITLE
Wasted Space Gap on Weapon Sheets

### ISSUE THREAD

**Issue by claycle** [HavlockV/CoC7-FoundryVTT#1018]
Noticed recently (after recent patch) that the weapon item sheet has an unusual wasted space gap:

![item-gap](https://user-images.githubusercontent.com/419840/156634588-3066aec2-381b-446e-bb95-d25ff4de59e4.jpg)

<img width="312" alt="image" src="https://user-images.githubusercontent.com/419840/156634639-65f83712-1c10-4d15-8f35-5d3d2c915352.png">

**Comment by claycle** [comment]
Also appears on Creature sheet:

<img width="545" alt="image" src="https://user-images.githubusercontent.com/419840/156671203-4f82603a-96e7-4a28-9c30-df6e160c497a.png">

**Comment by snap01** [comment]
Thanks for the report, #1025 resolves this
