### ISSUE TITLE
Sanity Loss field on NPC Sheet Style Not Matching Sheet (Too Large)

### ISSUE THREAD

**Issue by claycle** [HavlockV/CoC7-FoundryVTT#1019]
Noticed recently that the Sanity Loss field on NPC sheets does not match the styling of the rest of sheet (too large). In fact, it appears that the spacing on that row is off a little (probably as a result of the improper font):

<img width="217" alt="image" src="https://user-images.githubusercontent.com/419840/156635201-dff42637-11f2-4583-97c0-b3005655c122.png">

<img width="310" alt="image" src="https://user-images.githubusercontent.com/419840/156635393-86ea26ad-4dba-4d06-acd3-0bf10655ca27.png">

<img width="309" alt="image" src="https://user-images.githubusercontent.com/419840/156635235-faad12cb-8068-4cf3-9cef-d8e7db9abff2.png">

**Comment by snap01** [comment]
Thanks for the report, #1025 resolves this
