### ISSUE TITLE
I cant install it

### ISSUE THREAD

**Issue by conservate-lulu** [HavlockV/CoC7-FoundryVTT#1032]
I cant install this by using the following manifest

https://github.com/Miskatonic-Investigative-Society/CoC7-FoundryVTT/releases/latest/download/system.json

The VTT just tell me that you ofeer me a wrong manifest
![图片](https://user-images.githubusercontent.com/60819560/158053251-9ea260d4-9032-448c-afdd-9f1983d15e7f.png)

so how could i install this correctly

**Comment by snap01** [comment]
Can you please let us know the following?

- What operating system you are using?
- Are you using a web browser (which browser?) or the Electrum app?
- Are you able to open up the JavaScript console of your web browser/Electrum app and check if you get any error messages?
- Are you using the latest version of FoundryVTT?

**Comment by conservate-lulu** [comment]
i'm running it on windows server 2016 datacenter
using the exe file download from the official website
i'm able to run other rules like dnd5e,but have problem while installing your system from the list giving by the software
finally yes i'm using the latest version

besides now I have already installed it by replace address "latest" into the Exact version number(0.7.6)，i guess it may caused by the official Application mall，because the version write on it is only 0.6.4.
 
![2T}`_@}G(M(8LMM}{`13_H8](https://user-images.githubusercontent.com/60819560/159929663-36312287-327f-47d2-9951-36e8629c9fc8.png)
![@6@$UUK@NT9ACGS X649MEK](https://user-images.githubusercontent.com/60819560/159929989-7f1e8e4b-7d99-44f7-9d3d-ea3f18f7bb2b.png)

**Comment by gbraad** [comment]
Installing game systems while in China often fails due to intermittent connectivity with github.com
