### ISSUE TITLE
Text in Combat Rolls Not Displaying Correctly

### ISSUE THREAD

**Issue by claycle** [HavlockV/CoC7-FoundryVTT#1042]
We see several instances of text in combat rolls being ill-formatted, displaying in vertical columns rather than horizontally:

<img width="393" alt="Screen Shot 2022-03-20 at 3 13 17 PM" src="https://user-images.githubusercontent.com/419840/159186210-07543bb0-32f5-4649-97c1-8920090c4443.png">

**Comment by snap01** [comment]
This was resolved in #1034 and should be part of the next release
