### ISSUE TITLE
Label "Dodge" skill

### ISSUE THREAD

**Issue by frondeus** [HavlockV/CoC7-FoundryVTT#1044]
## Description.

Currently, the system detects the "dodge" skill by its name or translation.
This leads to quite difficult-to-spot bugs where translation might be slightly wrong or unexpected.

For example, in Polish, the only supported "Dodge" translation is "Uniki". However, since we do not provide translations to other languages for the items, a GM has to look at translation.json to find how one should name the skill. So it is "Uniki", not "Unik" or "Unikanie". What's more, some GMs might prefer to leave skills in the original English form.

Moreover, official campaign editions like "Maski Nyarlathotepa" use a different form - "Unik". (Since it is the official name of the skill in the "Podręcznik Badacza" - "Investigators Handbook") Every time GM imports a stat block, she needs to spot the error and correct it.

Another issue is - what if we agree that perhaps "Unik" sounds more natural in Polish? Well... We cannot just change it in the translation since that would break the mechanics for all GM's that have translated skills.

## Possible Implementation.

It is worth noting that all fighting skills work Out of the Box because we are just using labels to distinguish them from other skills. Perhaps there should be a particular "Dodge" label as well?
Then the mechanics would be entirely language-agnostic.

**Comment by everyonecancode** [comment]
I like the idea. Currently the Dodge skill name is dependant on Translator (who, let's be honest, can make a mistake, since this is a community project).

The other possible implementation would be to add a text box in System settings that would accept the name of a Dodge skill. Value of this field would be taken to determine the name of a Dodge skill. Similar to Insanity Table, but with Text Box, not a List.

**Comment by snap01** [comment]
The latest release has added a categorisation system which can be access from ID in the header.
If you set the skill ID to i.skill.dodge the system will detect this no matter the name of the skill.

**Comment by frondeus** [comment]
Thank you! It works! And I appreciate the automatic migration UI that scans all the NPCs and Investigators. It makes my life much much easier :)
