### ISSUE TITLE
NPC-Skillnames are not shown on the NPC-Sheet anymore

### ISSUE THREAD

**Issue by Muwak77** [HavlockV/CoC7-FoundryVTT#1072]
As the title says, i tested it with the previous version, where it worked fine. 

- [x] Are you running the latest version of both Foundry VTT and Call of Cthulhu 7th Edition?
- [x] Have you tested whether the bug persists without any other modules activated or on Foundry Launch in Safe Configuration?

## Description.

When I add a skill to the NPC-Sheet, i can add and edit it in the skill window where all date seems to be saved fine, but the name does not show on the sheet and any inline-edits in the skill-portion of the NPC-sheed is not stored. 

I tested this on my live and on my testsystem with and without active modules. 

## Expected Behavior.

The name should show on the sheet

## Actual Behavior.

Doesn't show

## Screenshots.
![image](https://user-images.githubusercontent.com/64545711/167911762-17096868-a32d-4015-b0b7-5c4a2d5094b5.png)

## Possible Fix.
Didn't check the source, sry tight timetable atm.

**Comment by snap01** [comment]
Thanks for the report this should be fixed in the next release.
