### ISSUE TITLE
New Skills won't show proper name

### ISSUE THREAD

**Issue by theczarek** [HavlockV/CoC7-FoundryVTT#1075]
### Prerequisites.

- [x] Are you running the latest version of both Foundry VTT and Call of Cthulhu 7th Edition?
Yes
- [x] Have you tested whether the bug persists without any other modules activated or on Foundry Launch in Safe Configuration?
Tested withot modules on new clear world

## Description.

When creating new skill on monster sheet skill is named "Nowa Umiejętność" despite of changing name in skill sheet. When changing of skill name directly on monster sheet it's reverted to default name. (Running Polish version).

When creating new skill in reporsitory and drag'n'drop it on sheet skill name is empty and cannot be changed.

Same goes for PC and NPC Sheets

**Comment by snap01** [comment]
Thanks for the report, this was resolved in #1073 and will be in a future release.
