### ISSUE TITLE
Query: Dice Rolling Sound Not Propagating to Other Players

### ISSUE THREAD

**Issue by Dick-K** [HavlockV/CoC7-FoundryVTT#1103]
I asked this question in #chaosium but didn't get any response, so I'm asking here.

I'm running CoC7 7.11. The sound of the dice rolling when the roll is generated from the CoC7 sheet is not echoed to other players.

I tried this with all modules off and this happens regardless of default roll mode. I can hear the dice rolling on the rolling player's machine but not on other connected sessions. I'm testing this between my GM machine and a separate laptop.

If I type "/r 1d6" into chat the dice roll is heard on the other sessions.

Playlists play correctly for all players, as do ambient sounds.

My query is: Is this as designed or am I experiencing a bug?

Thanks in advance.

**Comment by snap01** [comment]
Thanks for the report, audio is currently not pushed to other clients, this should be resolved in the next release

**Comment by Dick-K** [comment]
Thanks a lot for the confirmation.
