### ISSUE TITLE
During migration - Actor compendium - Empty array Items converted to empty string

### ISSUE THREAD

**Issue by vonv** [HavlockV/CoC7-FoundryVTT#1119]
Hi,

With all stuff up to date, i see error messages when migrating the system.
It concerns Actor Compendiums from my module: https://github.com/Trouver-Objet-Cache/coc7-module-fr-toc

When it migrates, in actors, it converts empty items for an actor, from an empty array [] to an empty string {}, showing an error message for each one.

![unknown](https://user-images.githubusercontent.com/44206935/175886406-46ecc88d-7e1b-4032-81cc-b193b3ce52f0.png)

**Comment by snap01** [comment]
Closing this issue as it has been resolved in the db files.
