### ISSUE TITLE
Cant load items after update

### ISSUE THREAD

**Issue by topper5282** [HavlockV/CoC7-FoundryVTT#1199]
After updating to 0.8.1 i am unable to open items, character sheets, skills etc.
all modules are turned off.
Using foundry V9 build 269
please see attached log from chrome console
[foundry error.log](https://github.com/Miskatonic-Investigative-Society/CoC7-FoundryVTT/files/9384251/foundry.error.log)

**Comment by HavlockV** [comment]
Hi topper5282,

Thanks for your report.
I had a look at the log.
Looks like the system cannot find the file active-effects.hbs in systems/CoC7/templates/common/
Could you check that the file is present in your data folder at the location it's supposed to and that you have valid rights set for this file.

**Comment by topper5282** [comment]
Since Latest update 0.8.2 the issue seems to have resolved itself 
thank you for your help
