### ISSUE TITLE
Unable to set HP on new Character, NPC or Creature sheets.

### ISSUE THREAD

**Issue by andy-jones** [HavlockV/CoC7-FoundryVTT#1206]
### Prerequisites.

- [Y ] Are you running the latest version of both Foundry VTT and Call of Cthulhu 7th Edition?
- [Y ] Have you tested whether the bug persists without any other modules activated or on Foundry Launch in Safe Configuration?

## Description.

On a newly created Character, NPC or Creature, I am unable to set the current HP. I can enter a value in the box, but when I press enter, that value disappears and the box remains blank.

## Expected Behavior.

You should be able to enter the HP value

## Actual Behavior.

Value you enter disappears when you press enter, leaving the HP field blank.

**Comment by snap01** [comment]
This was resolved in #1195 and should be included in the next release.
