### ISSUE TITLE
Difficult to edit notes on NPC Characters' Sheet

### ISSUE THREAD

**Issue by PaukPeck** [HavlockV/CoC7-FoundryVTT#1217]
Importing NPC's stats directly from PDF is a great fonctionality that save hours.
My problem is that after importing stats and creating the NPC's sheet, i can't edit further notes. 
When i click on the 'Edit" button, sometimes it works, but in most case, I can't write anything. The same thing for Keeper notes.
Any idea if i'm doing something wrong or if it's a problem with the NPC's sheet?

Thanks a lot !

### Prerequisites.

- [x ] Are you running the latest version of both Foundry VTT and Call of Cthulhu 7th Edition? yes
- [ x] Have you tested whether the bug persists without any other modules activated or on Foundry Launch in Safe Configuration? yes

**Comment by snap01** [comment]
Can you please confirm if this issue can be closed with the latest 0.9.1 release?

**Comment by PaukPeck** [comment]
Yes, no more problem since 9.0 versionThank you!

Envoyé depuis Yahoo Mail pour Android 
 
  Le lun., sept. 26, 2022 à 21:12, ***@***.***> a écrit:   


Can you please confirm if this issue can be closed with the latest 0.9.1 release?
