### ISSUE TITLE
Foundry 10.x Skills, Spells cannot be Dragged to Archetypes, Occupations, Setups, Books

### ISSUE THREAD

**Issue by Dick-K** [HavlockV/CoC7-FoundryVTT#1226]
On Foundry 10.283 and CoC7E 0.8.2, Skills cannot be dragged to Archetypes, Occupations and Setups. Spells may not be dragged to Books.

- [X] Are you running the latest version of both Foundry VTT and Call of Cthulhu 7th Edition?
- [X] Have you tested whether the bug persists without any other modules activated or on Foundry Launch in Safe Configuration?

## Description.

Attempting to drag Skills to Archetypes, Occupations and Setups or Spells to Books fails to register. No messages in console.

## Expected Behavior.

Skills and Spells should appear in receiving Item.

## Actual Behavior.

Attempting to drag Skills to Archetypes, Occupations and Setups or Spells to Books fails to register. No messages in console.

**Comment by level50miniatures** [comment]
I have the same problem, 
I drag the skills into the occupation but the program doesn't add it or get any message

**Comment by snap01** [comment]
A fix for this should be included in the next release
