### ISSUE TITLE
Location of participants in the Chase is not updated after each action

### ISSUE THREAD

**Issue by everyonecancode** [HavlockV/CoC7-FoundryVTT#1227]
### Prerequisites.

- [x] Are you running the latest version of both Foundry VTT and Call of Cthulhu 7th Edition?
- [x] Have you tested whether the bug persists without any other modules activated or on Foundry Launch in Safe Configuration?

## Description.
When creating a chase, where some actors have more than one action, their movement on Locations is updated only after all actions are used OR after clicking on any other element in the chase.

## Expected Behavior.
When using action, actors location is updated real time.

## Actual Behavior.
Actors location is updated only after all their actions are spent or after clicking on any location.

## Screenshots.
No screenshot, but a video. It shows two example participants, where one has 3 actions and the other has only 1 action. When token movement is enabled, you can seen in the video, that pressing "Move forward" button does nothing, unless you click on any locations or use all the actions.

[2022-09-05 20-30-34.webm](https://user-images.githubusercontent.com/15422337/188501254-e961f80d-e2a2-47e0-b735-1ae5c2ddc5f5.webm)

**Comment by HavlockV** [comment]
Corrected on develop
