### ISSUE TITLE
Unable to Create "Container" Actor

### ISSUE THREAD

**Issue by DMFSaint** [HavlockV/CoC7-FoundryVTT#1235]
### Prerequisites.

- [X] Are you running the latest version of both Foundry VTT and Call of Cthulhu 7th Edition?
- [X] Have you tested whether the bug persists without any other modules activated or on Foundry Launch in Safe Configuration?

## Description.

Unable to create Containers.

## Expected Behavior.

Clicking Create Actor, Typing in Name, and selecting Container should create a new Actor similar to the "Cubpoard" example.

## Actual Behavior.

Clicking Create Actor, Typing in Name, and selecting Container has no result.

**Comment by snap01** [comment]
A fix for this should be included in the next release

**Comment by DMFSaint** [comment]
Appreciate the update!

**Comment by snap01** [comment]
Can you please confirm if this issue can be closed with the latest 0.9.1 release?

**Comment by DMFSaint** [comment]
This issue is closed, thank you! I did notice something else that might be a bug. Will open a different ticket for it.

**Comment by DMFSaint** [comment]
Ignore other bug. It was with the Art/Any skill showing/rolling 10 despite the value being 5. Seems to be fixed in the second update since v.10 (9/27/22 today).
