### ISSUE TITLE
Text input adding tabulation if you're making a new line

### ISSUE THREAD

**Issue by JornieNonsubia** [HavlockV/CoC7-FoundryVTT#1248]
### Prerequisites.

- [x] Are you running the latest version of both Foundry VTT and Call of Cthulhu 7th Edition?
- [x] Have you tested whether the bug persists without any other modules activated or on Foundry Launch in Safe Configuration?

## Description.

Steps:
Enter text into any text input
Press Enter or any other Key combination to start writing in new line
Enter text again

## Expected Behavior.

We should be able to write text from a new line, so we could organize info as we want to

## Actual Behavior.

Any time we click at text input, regardless have we enter new info or not it adds tabulation or a lot of spaces

## Screenshots.
![image](https://user-images.githubusercontent.com/31547291/191230161-c31f402a-7b7f-4322-8d4b-18ac9cd720d8.png)
![image](https://user-images.githubusercontent.com/31547291/191230203-9ca1d00f-6fc8-4428-a1ee-acc3e6e850aa.png)
![image](https://user-images.githubusercontent.com/31547291/191230586-bdc3f0b0-1717-4221-a41b-77daceda84f1.png)

## Possible Fix.

Seems like it there is an issue in saving the text

**Comment by snap01** [comment]
A fix for this should be included in the next release

**Comment by snap01** [comment]
Can you please confirm if this issue can be closed with the latest 0.9.2 release?
