### ISSUE TITLE
Development Phase cites checked skills as "undefined" in chat message.

### ISSUE THREAD

**Issue by Dick-K** [HavlockV/CoC7-FoundryVTT#1261]
When clicking the Devlopment Phase button, the chat message for each checked skill identifies the skill as "undefined". It foes, however, correctly roll for the skill's development.
### Prerequisites.

- [Y] Are you running the latest version of both Foundry VTT and Call of Cthulhu 7th Edition?
- [Y] Have you tested whether the bug persists without any other modules activated or on Foundry Launch in Safe Configuration?

## Description.
See summary.
Bug detected in Foundry v10. Bug does not occur on Foundry v9. Bug exists for PCs migrated from v9 and for new PC created in v10.

## Expected Behavior.
Chat message should identify the skill correctly by its name.

## Actual Behavior.
See summary.

## Screenshots.
![image](https://user-images.githubusercontent.com/73724728/192895696-6235ae73-f8b0-4883-896e-57e0aae59fb3.png)

**Comment by snap01** [comment]
A fix for this should be included in the next release

**Comment by snap01** [comment]
Can you please confirm if this issue can be closed with the latest 0.9.2 release?

**Comment by Dick-K** [comment]
Yes, that's displaying the skill name correctly now. Many thanks!
