### ISSUE TITLE
Links to headers in journal pages don't work

### ISSUE THREAD

**Issue by superseva** [HavlockV/CoC7-FoundryVTT#1273]
### Prerequisites.

- [x] Are you running the latest version of both Foundry VTT and Call of Cthulhu 7th Edition?
- [x] Have you tested whether the bug persists without any other modules activated or on Foundry Launch in Safe Configuration?

## Description.

Create an UUID link that uses ```#``` to link to a header tag in some other journal page.
This should be default Foundry behavior

## Expected Behavior.

Links like @UUID[JournalEntry.tgwST2KeEd3tqW7O.JournalEntryPage.hk1Ks8kNl4RA4R2a#my-header]{My Header}
should open journal page and scroll to header.

## Actual Behavior.

Journal page opens but it doesn't scroll to the header.
This also causes problems with other links that are using hashtag ``` # ``` in their url to send optional attributes to the links. (Like PDF Pager is sending page number after the ``` # ``` symbol

**Comment by snap01** [comment]
A fix for this should be included in the next release

**Comment by snap01** [comment]
Can you please confirm if this issue can be closed with the latest 0.9.2 release?

**Comment by superseva** [comment]
It works as it’s intended now. Fixed.
