### ISSUE TITLE
secret blocks are no more secrets in items

### ISSUE THREAD

**Issue by PaukPeck** [HavlockV/CoC7-FoundryVTT#1279]
I don't want my players to see every informations on items like spells, etc..., so in the description part of the items i enter secret blocks. But when i drag/drop items in the character sheet, the player can see everything in the secret block !
![secret block items](https://user-images.githubusercontent.com/46634593/194843380-eb725f19-e351-4ed2-8344-67cf645b1bda.JPG)

And if i open the item as GM, secret block is not visible if i am not in edit mode, so it's not very easy to see informations

**Comment by PaukPeck** [comment]
Sorry, i don't find how to edit my comment to label it as a bug....

**Comment by snap01** [comment]
A fix for the secrets not being visible unless editing should be included in the next release.

The secret blocks are part of Foundry VTT and will show up for anyone with ownership rights of Owner for the Actor that contains the item or the Item itself.

Each sheet should have a symbol on the tabs for Keeper notes which can be used for notes only the Keeper can see.

**Comment by snap01** [comment]
Can you please confirm if this issue can be closed with the latest 0.9.2 release?

**Comment by PaukPeck** [comment]
Yes, you can close the issue. thank you very much for the answer and the fast resolution of the issue !

    Le mardi 18 octobre 2022 à 10:27:04 UTC+2, snap01 ***@***.***> a écrit :  
 
 


Can you please confirm if this issue can be closed with the latest 0.9.2 release?
