### ISSUE TITLE
Character importer / SAN Loss

### ISSUE THREAD

**Issue by vonv** [HavlockV/CoC7-FoundryVTT#1285]
Bug tested on the french import.

If the character to import as no SAN in the text, the SAN Loss won't be computed.
You have to add "SAN 0".

**Comment by snap01** [comment]
A pull request (#1318) has been made so that if "SAN" or "Santé Mentale" is prefixed by "de " it is not parsed as a SAN value, can you please confirm if this would be acceptable?
