### ISSUE TITLE
Cannot Lock Character Sheets, Lock button not working

### ISSUE THREAD

**Issue by TollhouseC** [HavlockV/CoC7-FoundryVTT#1290]
**Description:**
After upgrading to v10, the character sheets show the below option and are permanently in the unlocked position.
![25oHwbb](https://user-images.githubusercontent.com/76264029/202050717-34ed6466-605a-4ce9-aaf7-f4da0e64a8f6.png)

Players cannot use rolls now outside of using the "summarize" view, and cannot apply or see their earned successful rolls

**Comment by kwitczak** [comment]
Hey @TollhouseC, does it still happen? I tried to repro this on v10, build `291` and CoC `0.9.2` and the lock worked as expected.

**Comment by TollhouseC** [comment]
Nope works fine in most recent version of foundry and CoC
