### ISSUE TITLE
Attacs per round filed clears itself

### ISSUE THREAD

**Issue by theczarek** [HavlockV/CoC7-FoundryVTT#1294]
"Attacs per round"  filed  on Monster sheet clears itself when first time edite and ecery time monster sheet is unlocked.
Same goes for NPC sheet

- [X ] Are you running the latest version of both Foundry VTT and Call of Cthulhu 7th Edition?
- [X] Have you tested whether the bug persists without any other modules activated or on Foundry Launch in Safe Configuration?

**Comment by TheHalf12** [comment]
I've been having this issue still, could it be that my version has not been updated? I tried looking for updates in foundry but didn't find any.

**Comment by snap01** [comment]
The fix for this is in the code and will be included in the next release.
