### ISSUE TITLE
Apply custom skill modifier to a character (ask for advice)

### ISSUE THREAD

**Issue by PaukPeck** [HavlockV/CoC7-FoundryVTT#1304]
Hi,
this post is more a question than a enhancement, but it would be great to have an answer: 

I don't know if it's already possible but i would like to add some new effects to those already in the system (unconscious, temporary insanity, etc...). 
In French v6 Cthulhu rules, there are several states of health  that i would find interesting to add like "Epuisé" (exhausted) where all the action skills have -20% and the other skills -10%. 
I would be very cool to have these modifiers being automatic via Foundry effects but i didn't find the path to modify a character's skill via effects.
Is it possible to do that with the coc system as it is ? And if it's possible, how to do it ?

Thanks !

**Comment by kwitczak** [comment]
@PaukPeck It's not ideal but it's possible. 

1. Go to **Items** section
2. Add a new item and make it a type `status`
3. Open a small icon on the right side called **Effects**
4. Add new Effects associated with the new status. These little things can modify certain `attributes`, they can be timed and described nicely.
5. You can access Strength using this: `system.characteristics.str.value` and modify it using the dropdown.
6. More information (on attributes, how to get them and so con) can be found in **Compendium/System Manual/Effects**.

See the picture below for reference.
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/8782549/221959756-e451dad2-8f5b-46ad-886b-3b44272f9626.png">

When you will drag this item onto a Character sheet, it will apply status and it's effects.
<img width="803" alt="image" src="https://user-images.githubusercontent.com/8782549/221960708-72438c66-eab2-4b5e-85e1-7dd71c9f1f3a.png">

**Comment by kwitczak** [comment]
Maybe I've found a potential bug because it seems that... only functions **Add** and **Override** work as expected...

When I added `-10` it reduced the example character STR from 50 to 40.
However, when I multiplied by `0.70` it seems to create a string out of it, which looks like a type-casting bug (?).
@snap01 I'll take a look at this later.

<img width="297" alt="image" src="https://user-images.githubusercontent.com/8782549/221961506-a18975d1-e790-4d00-8409-492919d352df.png">

**Comment by PaukPeck** [comment]
Wow, thanks a lot !I will try this as soon as possible :D
Envoyé depuis Yahoo Mail pour Android 
 
  Le mar., févr. 28, 2023 à 20:43, Krzysztof ***@***.***> a écrit:   


Maybe I've found a potential bug because it seems that... only functions Add and Override work as expected...

When I added -10 it reduced the example character STR from 50 to 40.
However, when I multiplied by 0.70 it seems to create a string out of it, which looks like a type-casting bug (?).
@IkeoMajesty , @snap01 I'll take a look at this later.

**Comment by kwitczak** [comment]
@PaukPeck I just did an MR which makes `multiplication` work as expected with floating numbers - problem I mentioned above in the comments. 😸 

In other words, it should be possible for you to achieve this result soon:
> (...) where all the action skills have -20% and the other skills -10% (...)

**Comment by PaukPeck** [comment]
It works perfectly, thank you very much !!!
btw, is the official foundry chaosium's call of cthulhu coming soon ???

    Le mercredi 1 mars 2023 à 18:33:50 UTC+1, Krzysztof Witczak ***@***.***> a écrit :  
 
 


@PaukPeck I just did an MR which makes multiplication work as expected with floating numbers - problem I mentioned above in the comments. 😸
 
In other words, it should be possible for you to achieve this result soon:


(...) where all the action skills have -20% and the other skills -10% (...)

**Comment by PaukPeck** [comment]
Is there a way to affect a whole family of skills at once : for example Arts & Crafts, Languages, and son on?
