### ISSUE TITLE
Newly added skill in NPC/Creature character sheet doesn't use base skill value

### ISSUE THREAD

**Issue by kwitczak** [HavlockV/CoC7-FoundryVTT#1305]
### Prerequisites

- [x] Are you running the latest version of both Foundry VTT and Call of Cthulhu 7th Edition?
- [x] Have you tested whether the bug persists without any other modules activated or on Foundry Launch in Safe Configuration?

## Description

Steps to reproduce:
1. Using Foundry `v10, build 291` and CoC 7 `0.9.2`, set up a new game.
2. Import "Creature example" from Compendium, Actor examples.
3. Open "Creature example" sheet.
4. Unlock the sheet using the lock icon.
5. Click ➕ icon in "Skills" section.
6. Set `name` to `"Chomp"` and set `base` to `20`.
7.  Save.

## Expected Behavior

8.  Skill `"Chomp"` is displayed in the "Skills" section with a value of `20`, which can be modified. This is how it works for Character sheets and players and it's useful when adding skills to NPC in a rush during the game.

## Actual Behavior

8.  Skill `"Chomp"` is displayed in the "Skills" section but its value is empty, forcing us to manually edit it to set the value to `20`. 

## Screenshots.

<img width="874" alt="Screenshot 2023-02-26 at 21 18 35" src="https://user-images.githubusercontent.com/8782549/221431971-4c2e174c-018e-4567-8614-9fd94f0ff675.png">

## Possible Fix.

Use a fallback mechanism for skills.
1. Use `user-defined-value` if it exists.
2. If not, use `base-value` if it exists.
3. If not, leave it blank as it is now.

**Comment by snap01** [comment]
Thank you, your pull request has been merged
