### ISSUE TITLE
Creature HP cannot exeed 99

### ISSUE THREAD

**Issue by SirKostya** [HavlockV/CoC7-FoundryVTT#1314]
Whenever I set a creatures HP above 99 points it automatically sets it back to 99, even when max HP would allow a higher number.

- [Y] Are you running the latest version of both Foundry VTT and Call of Cthulhu 7th Edition?
- [Y] Have you tested whether the bug persists without any other modules activated or on Foundry Launch in Safe Configuration?

Many monsters, especially deities, have HP higher then 99.

There should be no artificial barrier preventing a Keeper from setting a desired HP value.

![CreatureHpBug](https://user-images.githubusercontent.com/128192291/226065121-b4f08709-c3e5-4079-9c0e-4b876c65a428.png)

**Comment by kwitczak** [comment]
Thanks @SirKostya, I noticed this problem as well on my last session. I'll work on fixing it this week 💪 
Good luck with Cthugha, seems it will be a tough encounter... 😉
