### ISSUE TITLE
Freeze with 100% cpu due to invalid regexp

### ISSUE THREAD

**Issue by kakaroto** [HavlockV/CoC7-FoundryVTT#1316]
A user reported the issue of their games freezing on launch, with the browser tab becoming unusable.
After investigation, it appears to be due to a bad regular expression which causes the browser to take 100% CPU and never return.

You can reproduce this fairly easily in a console tab with the following code:
```js
Array.from(`@coc7.effect[{"label":"Affinity - Devoted", "Icon":"`.matchAll(/@(coc7)\.([^\]]+?)\[((?:[^\]\[]+|\[(?:[^\]\[]+|\[[^\]\[]*\])*\])*)\](?:{([^}]+)})?/gi))
```

The user said it happened when they used "the status-effect-link-thing-in-the-dialogue".

The issue is happening on Foundry 10.291 with CoC7 0.9.2. This is the chat message that triggers it:
```html
    <header class="message-header flexrow">
        <h4 class="message-sender">Gamemaster</h4>
        <span class="message-metadata">
            <time class="message-timestamp">19h ago</time>
            <a class="message-delete"><i class="fas fa-trash"></i></a>
        </span>


    </header>
    <div class="message-content">
        <div class="effect-message">@coc7.effect[{"label":"Affinity - Devoted","icon":"<a class="hyperlink" href="https://assets.forge-vtt.com/62496affc12b2440331ca2f5/crown.png&quot;,&quot;changes&quot;:[{&quot;key&quot;:&quot;data.skills.Affinity" target="_blank" rel="nofollow noopener">https://assets.forge-vtt.com/62496affc12b2440331ca2f5/crown.png","changes":[{"key":"data.skills.Affinity</a> Compliance.value","mode":2,"value":"+35"}],"tint":"#feea16","duration":{"seconds":null,"rounds":1,"turns":10}}]{}</div>
    </div>
```

The offending code is in `module/apps/coc7-parser.js` where the regex in `enrichHTML`.
```js
    text = TextEditor._getTextNodes(html)
    const rgx = new RegExp('@(coc7)\\.' + '([^\\]]+?)' + '\\[((?:[^\\]\\[]+|\\[(?:[^\\]\\[]+|\\[[^\\]\\[]*\\])*\\])*)\\]' + '(?:{([^}]+)})?', 'gi')
    TextEditor._replaceTextContent(text, rgx, CoC7Link._createLink)
```
Since only text nodes are taken, we end up with 3 text nodes being sent to `_replaceTextContent`, since there's a `<a>` anchor in the middle of it.
![image](https://user-images.githubusercontent.com/27990/226927339-dc7f4463-2130-472a-9ba8-021b02407b58.png)

So you end up with the regexp being applied to the string `@coc7.effect[{"label":"Affinity - Devoted", "Icon":"` which causes it to freeze inside the `_replaceTextContent`.

## Possible Fix
You can test the regexp here, and watch out for the `ERROR` on the right which says it's taking longer than 250ms to process the regexp (it should ideally be under 1ms)
https://regexr.com/7amt1

Looking at the regexp, I can see a couple of issues. I'm not entirely sure what it is exactly trying to search for, but I think you want to match anything inside the `[]` including any content that contains nested brackets. You start with `@coc7.` then any characters that aren't `]` while I think it should be any chars that aren't `[` instead. Then inside the `[ ]` group, your issue is that you use a nested quantifier (match one or more, then match multiple times). The `(.+)*` is what trips it, and doing a recursion in regexp is not really supported because of that. What you can do though is to linearize it and decide how many nested brackets you want to have. See the following regexp which works for up to two nested brackets.

https://regexr.com/7amue

Suffice to say, it won't be an easy thing to solve with regexp, and if you need nested brackets, it might be better to just have it match until the last `]` in the text, then have the callback function recursively do smaller regexp on the captured groups. A simple solution could just be to match for `\[(.*)\]` to match everything inside the brackets. (https://regexr.com/7amv0)
Up to you to decide what's best here, since you know better what the purpose of the regexp is.
I hope this helps.

**Comment by snap01** [comment]
Thanks for the detailed report. Limiting the system to two sets of nested square brackets covers all the link types, this change will be included in the next release for the 100% CPU issue.

Additional changes will still need made to prevent external links being malformed
```@coc7.effect[{"label":"Affinity - Devoted","icon":"https://assets.forge-vtt.com/62496affc12b2440331ca2f5/crown.png","changes":[{"key":"data.skills.Affinity Compliance.value","mode":2,"value":"+35"}],"tint":"#feea16","duration":{"seconds":null,"rounds":1,"turns":10}}]{}```
will render as
```@coc7.effect[{"label":"Affinity - Devoted","icon":"<a class="hyperlink" href="https://assets.forge-vtt.com/62496affc12b2440331ca2f5/crown.png&quot;,&quot;changes&quot;:[{&quot;key&quot;:&quot;data.skills.Affinity" target="_blank" rel="nofollow noopener">https://assets.forge-vtt.com/62496affc12b2440331ca2f5/crown.png","changes":[{"key":"data.skills.Affinity</a> Compliance.value","mode":2,"value":"+35"}],"tint":"#feea16","duration":{"seconds":null,"rounds":1,"turns":10}}]{}```
