### ISSUE TITLE
Active Effect Repeats Change to Actor

### ISSUE THREAD

**Issue by Dick-K** [HavlockV/CoC7-FoundryVTT#1320]
An item Active Effect that adds/subtracts to an Actors charactistic (e.g.POW) is re-run every time the Actor sheet is opened, resulting in the change to the value accruing.
An item Active Effect that adds/subtracts to an Actors attribs is run only once, when the item is dragged to the Actor's inventory. It is assumed this is the correct behaviour.

- [Y] Are you running the latest version of both Foundry VTT and Call of Cthulhu 7th Edition?
- [Y] Have you tested whether the bug persists without any other modules activated or on Foundry Launch in Safe Configuration?

## Description.

An item Active Effect that adds/subtracts to an Actors charactistic (e.g.POW) is re-run every time the Actor sheet is opened, resulting in the change to the value accruing.

An item Active Effect that adds/subtracts to an Actors attribs is run only once, when the item is dragged to the Actor's inventory. It is assumed this is the correct behaviour.

## Expected Behavior.

Active Effect is run only once, whether a characteristic or attribs data path.

## Actual Behavior.

See above.

## Possible Fix.

Unknown. I appreciate that the official CoC implementation is taking your time so perhaps just leave this as a note for that version?

**Comment by snap01** [comment]
A fix for this should be included in the next release

**Comment by Dick-K** [comment]
Many thanks :)
