### ISSUE TITLE
Can't create character with Investigator Creation Wizard, if occupation contains optional skills

### ISSUE THREAD

**Issue by marcstraube** [HavlockV/CoC7-FoundryVTT#1342]
### Prerequisites.

- [X] Are you running the latest version of both Foundry VTT and Call of Cthulhu 7th Edition?
- [X] Have you tested whether the bug persists without any other modules activated or on Foundry Launch in Safe Configuration?

## Description.

I'm trying to pre-create the occupations for my players, so that they can use the Investigator Creation Wizard. This works well, as long as the occupation does not contain optional skills. As soon as I add those, I can't complete the dialog, where I have to chose the occupation skills, because it requires me to chose a couple hundred to thousand (depending on how many optional skills).

## Expected Behavior.

In the screenshots you can see two occupations I've created. The only difference is that the 2nd occupation contains an optional skill with multiple options. When I chose the 1st occupation in the Investigator Creation Wizard it requires me to set the correct amount of 5 occupation skills. With the 2nd occupation it should require a total of 6 occupation skills.

## Actual Behavior.

When the 2nd occupation is chosen, the Wizard wants me to chose between 501 skills. The Next Button won't show up.

I've tested some more and added a second optional skill group to "Occupation 2". Now the wizard wants me to select 5011 skills.

## Screenshots.

![occupations](https://github.com/Miskatonic-Investigative-Society/CoC7-FoundryVTT/assets/52066916/1eee0888-0de0-45c8-b617-efab499d71ee)
![occupation1-skills](https://github.com/Miskatonic-Investigative-Society/CoC7-FoundryVTT/assets/52066916/a79b6f80-2364-4864-9a75-10f08bb08f9f)
![occupation2-skills](https://github.com/Miskatonic-Investigative-Society/CoC7-FoundryVTT/assets/52066916/988a2666-5b55-4106-ab6b-7f1aa9d6773d)

**Comment by marcstraube** [comment]
I just cloned the repos and was about to fix the bug, but found, that it was already fixed within this commit:
https://github.com/Miskatonic-Investigative-Society/CoC7-FoundryVTT/commit/c4dcf9607fedb92aad708fdc8d6dec2cc3d029af

**Comment by snap01** [comment]
A fix for this has been added to the latest release
