### ISSUE TITLE
Roll requests from chat cards 

### ISSUE THREAD

**Issue by Lockbox313** [HavlockV/CoC7-FoundryVTT#1348]
### Prerequisites.

- [ ] Are you running the latest version of both Foundry VTT and Call of Cthulhu 7th Edition?
- [ ] Have you tested whether the bug persists without any other modules activated or on Foundry Launch in Safe Configuration?

## Description.

Since the last update roll requests  sent to chat are no longer working.  This is happening from the sheet and the macros journal entries. 
[](https://discord.com/channels/170995199584108546/751202546512691331/1116287517109526610)

## Expected Behavior.

When the player clicks the button on the chat card it should roll the skill

## Actual Behavior.

Nothing, Roll is not made and the no errors appear in the Console.

**Comment by snap01** [comment]
A fix for this has been added to the latest release
