### ISSUE TITLE
French localization induces strange characters and breaks dodging and other mechanics

### ISSUE THREAD

**Issue by PicoTN** [HavlockV/CoC7-FoundryVTT#1368]
I am hosting an instance on The Forge. When switching the foundry language to French (which is my mother tongue and the language e play in), weird §§§ symbols get added in a few places and seem to break the ID system.

## Description.

These §§§ characters appear when switching the FoundryVTT Language preference to French and show up in a few places, but mainly on front of some of the important game IDs
![my French dodge skill](https://github.com/Miskatonic-Investigative-Society/CoC7-FoundryVTT/assets/115478774/3cb93695-59f5-4363-82ad-690a728d5575)
![the original compendium English dodge skill](https://github.com/Miskatonic-Investigative-Society/CoC7-FoundryVTT/assets/115478774/971b79fc-93f2-451e-a22f-94e5b2994312)

When in combat, the "dodging" option is then unavailable, despite the character or creature possessing the skill (I even tested giving the creature both the English and French version)
![dodge is not available](https://github.com/Miskatonic-Investigative-Society/CoC7-FoundryVTT/assets/115478774/63addc1f-9ec5-470e-bcea-5b1b5041109a)
![the test creature used](https://github.com/Miskatonic-Investigative-Society/CoC7-FoundryVTT/assets/115478774/f6983b22-2015-419b-872f-442758feb2d2)

When switching back the language preference to English, however, the English version of the skill gets detected correctly and the strange §§§ symbols no longer show up (but the french version of the skill is still undetected, but this might be intended behaviour.

![Working in English](https://github.com/Miskatonic-Investigative-Society/CoC7-FoundryVTT/assets/115478774/65b778db-2c1b-4eb9-9764-77be77052f3b)

My guess (which might seem obvious) is that those characters break the function responsible of finding specific skills, but I have no idea where they come from.
This also seems to impact the credit rating (and the assets calculations)
![credit rating](https://github.com/Miskatonic-Investigative-Society/CoC7-FoundryVTT/assets/115478774/29da3166-5a82-4565-b0df-974ff5643d7b)
assets are miscalculated; credit has a value of 85 here, assets and expenses should be way higher
![assets are miscalculated; credit has a value of 85 here](https://github.com/Miskatonic-Investigative-Society/CoC7-FoundryVTT/assets/115478774/e7166c90-60c9-4067-acb3-410f64789b07)

and the Cthulhu Mythos skill (and the maximum sanity value calculation)

![cthulhu mythos](https://github.com/Miskatonic-Investigative-Society/CoC7-FoundryVTT/assets/115478774/cf448ab2-af68-4864-8e0f-5d759513fb95)
mythos is at 5 max should be at 94
![mythos is at 5 max should be at 94](https://github.com/Miskatonic-Investigative-Society/CoC7-FoundryVTT/assets/115478774/0cb7099b-79a2-4a6a-8a28-bd7a55f87aaa)

**Comment by snap01** [comment]
The skills not be detected will be fixed in the next release.

**Comment by PicoTN** [comment]
Thank you very much. I wanted to look into the code today and found the §§§ in the untranslated French language file. I would have finished the translation if someone weren't already done with it, thank you so much ! If French translators are needed in the future, I am totally available (I will try to join the Discord sometime this week)
Thank you also for fixing the look-up issue, my players and I are really thankful !
