### ISSUE TITLE
Doors visible with no light sources and global illumination turned off

### ISSUE THREAD

**Issue by Lockbox313** [HavlockV/CoC7-FoundryVTT#1387]
### Prerequisites.

- [x] Have you checked the Upcoming Release section of the changelog to see if the issue will be resolved in the next release? https://github.com/Miskatonic-Investigative-Society/CoC7-FoundryVTT/blob/develop/.github/CHANGELOG.md
- [ ] Are you running the latest version of both Foundry VTT and Call of Cthulhu 7th Edition?
- [x] Have you tested whether the bug persists without any other modules activated or on Foundry Launch in Safe Configuration?

## Description.
I am running Foundry 10.303 and COC7 version 0.10.5
Doors are visible to players when  global illumination is disabled  and there are no light sources.  Using versions 0.10.5 and 0.10.3 I have tried disabling all modules, launching in safe mode, creating a new world all with the same result.  I have  tested this with multiple other systems and none of them show doors there is no global illumination or light sources.

## Expected Behavior.
Doors should not be shown when there is no global illumination and when no light source is illuminating them.

## Actual Behavior.

Doors are shown

## Screenshots.

![image](https://github.com/Miskatonic-Investigative-Society/CoC7-FoundryVTT/assets/8994813/4dbca854-945c-4ea0-95d7-a4627813529d)

![image](https://github.com/Miskatonic-Investigative-Society/CoC7-FoundryVTT/assets/8994813/4845b3bc-1055-441c-a2a9-a7c07d86401a)

**Comment by snap01** [comment]
This is controlled in the token config, Vision, Detection Modes, removing the basic vision will prevent this

**Comment by Lockbox313** [comment]
Thank You.
