### ISSUE TITLE
Skills should be items from Compendium, but instead multiple Charsheets should exist for each era

### ISSUE THREAD

**Issue by apoapostolov** [HavlockV/CoC7-FoundryVTT#14]
Instead having a single Charsheet and having to add manually all skills relevant to an era, you should make multiple character sheets with predefined sets and defaults for each skill. This way the game will still support multiple eras but the DM chooses what character sheet is default from the System Settings.

**Comment by HavlockV** [comment]
Very good point. The complexity of having this era prop on skills is too complicated to handle.
I'll keep that in mind for a future release.
K.I.S.S ! ;)

**Comment by HavlockV** [comment]
Included in last commit
