### ISSUE TITLE
Lock / Unlock / Roll / mode change not supported on actors in compendium

### ISSUE THREAD

**Issue by chuffdecki** [HavlockV/CoC7-FoundryVTT#1432]
### Prerequisites.

- [ X ] Have you checked the Upcoming Release section of the changelog to see if the issue will be resolved in the next release? https://github.com/Miskatonic-Investigative-Society/CoC7-FoundryVTT/blob/develop/.github/CHANGELOG.md
- [ X ] Are you running the latest version of both Foundry VTT and Call of Cthulhu 7th Edition?
- [ X ] Have you tested whether the bug persists without any other modules activated or on Foundry Launch in Safe Configuration?

## Description.

When adding or modifying an actor within the compendium you can not alter the mode, roll stats, or lock and unlock the character. Those buttons do nothing when clicked and give no indication as to why they failed to the user. In order to create an actor with formula in the compendium you must first create it in the actor pane then copy it into a compendium. The same must be done when you modify the actor in the compendium, copy to actor pane, delete from compendium, modify in actor pane, copy back to compendium.

## Expected Behavior.

The actor sheet should work exactly the same in compendium and actor panes. If there are features you do not want in the compendium actor sheet for any reason, the button for that action should not exist, or clicking it should alert the user that the feature is only available in the actor pane. It took me so long to figure out what was wrong, and how to fix it, because of the lack of feedback.

## Actual Behavior.

None of the buttons in the screenshot below work in a character sheet opened from a compendium. They all work on an actor sheet opened from the actor pane.

## Screenshots

![Screenshot 2023-11-10 at 8 47 00 AM](https://github.com/Miskatonic-Investigative-Society/CoC7-FoundryVTT/assets/141275049/d6168955-4e94-4276-96b7-44a349f91b89)

**Comment by HavlockV** [comment]
Corrected with #1430
