### ISSUE TITLE
Ability to enter MOV score manually.

### ISSUE THREAD

**Issue by Fusekki** [HavlockV/CoC7-FoundryVTT#1466]
Ability to enter MOV score manually.

Currently the MOV score is calculated based on the attributes entered. It would be nice if this can be modified as well.

**Comment by snap01** [comment]
Hello, you can either
* Unlock the character sheet and click on Mov to edit the value directly to prevent automatic calculation.
* Add an active effect for "system.attribs.mov.value" "Add" "-2" to dynamically increase or decrease the value.

**Comment by Fusekki** [comment]
"Unlock the character sheet and click on Mov to edit the value directly to prevent automatic calculation."

Unlocking the Actor does not allow me to modify the value directly.  Just an FYI.

**Comment by snap01** [comment]
While the character sheet is unlocked you have to click on the text Mov which will toggle the value next to it between automatic calculation and an input box for manual entry.

**Comment by Fusekki** [comment]
That does not work. The field remains read-only.

**Comment by snap01** [comment]
To set the value on the NPC/Creature sheet you need to click the two cogs to toggle between automatic calculation and manual.

What versions of FoundryVTT and the CoC7 system are you using?

Does if still not work if you disable all modules?

With the character sheet unlocked if you hover over the word Mov for three seconds do you get a tooltip for Automatic calculation toggle?

**Comment by Fusekki** [comment]
The hover does display the popup mentioned. However, when I left click it does not change the field to editable. As for the NPC sheet, I can't seem to locate the cogs you mentioned.  I have attached some GIFs to help illustrate my difficulty.  I've also attached some screenshots indicating both the version of Foundry and the world version.

![cthulhu_world_version](https://github.com/Miskatonic-Investigative-Society/CoC7-FoundryVTT/assets/12960670/c1bdf207-7c48-4104-a799-89748d05020b)
![foundry_version](https://github.com/Miskatonic-Investigative-Society/CoC7-FoundryVTT/assets/12960670/cf82c22e-4bf0-48bf-927e-5c2651841ff4)
![Foundry_Virtual_Tabletop_shybJ5QJim](https://github.com/Miskatonic-Investigative-Society/CoC7-FoundryVTT/assets/12960670/2700b35c-f749-40dd-8832-8d4b16dd2077)
![Foundry_Virtual_Tabletop_ypeC8OvuLG](https://github.com/Miskatonic-Investigative-Society/CoC7-FoundryVTT/assets/12960670/b631a730-c020-4eb6-9b4f-f4219893c1fc)

**Comment by snap01** [comment]
Thank you for the screenshots, currently the sheets can not toggle between automatic calculation and manual while in compendiums.

The cogs I meant for the npc/creature sheets are the green ones to the right of the numbers, but these can also not be toggled while in a compendium.

**Comment by Fusekki** [comment]
Ok. Thanks for all the help!
