### ISSUE TITLE
Players see "Rollable detected" even without permission to actor

### ISSUE THREAD

**Issue by sebastienlaughrea** [HavlockV/CoC7-FoundryVTT#1500]
When the Gamemaster drags an actor with rollable characteristics onto the map, both the Gamemaster and the players receive a message, "This token has rollable characteristics or skills. What do you want to do?"
It is normal for the Gamemaster to see this but the players, who don't have permissions to the actor, shouldn't see the message.

![Player View](https://github.com/Miskatonic-Investigative-Society/CoC7-FoundryVTT/assets/54970742/3fb0c8dd-8124-4777-be96-4e8a05bd0f70)

**Comment by daggerfortysix** [comment]
I am having this same issue in v010.11, but it looks like you all may have a fix. Is it supposed to be fixed in v0.10.11 or is it going to be on the next version?
