### ISSUE TITLE
NPCs / Creatures cannot be added to scene

### ISSUE THREAD

**Issue by co-de-pot** [HavlockV/CoC7-FoundryVTT#1515]
### Prerequisites.

- [x] Have you checked the Upcoming Release section of the changelog to see if the issue will be resolved in the next release? https://github.com/Miskatonic-Investigative-Society/CoC7-FoundryVTT/blob/develop/.github/CHANGELOG.md
- [x] Are you running the latest version of both Foundry VTT and Call of Cthulhu 7th Edition?
- [x] Have you tested whether the bug persists without any other modules activated or on Foundry Launch in Safe Configuration?

## Description.

When trying to add a NPC or Creature token to a scene via drag-and-drop, they do not appear on the scene. 
Leaving the scene and trying to load it again has the loading bar stuck. The only method of leaving such a stuck scene is either launching the world in safe mode (to unload the scene) or deleting the whole scene altogether.

## Expected Behavior.

The NPC/Creature token should appear just as Character/Container tokens.

## Actual Behavior.

The NPC/Creature token does not appear and causes the whole scene to fail loading

## Reproduction Steps.

1. Create a new world using this system
2. Import the "Examples" compendium pack
3. Drag-and-drop the "Goon", "Villian example" or "Creature example" into the scene
4. (optional) switch scenes and try to load back into the scene.

I also included an exported minimal example scene with [this file](https://github.com/Miskatonic-Investigative-Society/CoC7-FoundryVTT/files/14666886/fvtt-Scene-test-scene-A9oigFoGHKyaWiA4.json).

**Comment by snap01** [comment]
You can load the scene in a Chromium based browser and remove the tokens using SVGs your browser doesn't support.

Resolved with #1517, to be included in the next release
