### ISSUE TITLE
Enable CoC Id in links for checks

### ISSUE THREAD

**Issue by acd-jake** [HavlockV/CoC7-FoundryVTT#1530]
## Description.

Links for checks should be able to use the CoC ID as an alternative to the name, as the names of skills or items depend on the localization.

## Context.

For the localization of the CoC system, it is not useful to have to specify the name of the skill or item in the links for skill checks or item checks. Alternatively, it should be possible to enter the CoC ID here, which is separate from the localized name of the skill or item.

This would make it possible to use links for checks in journals written in a language other than the one currently set in the Foundry during the game.

For example: I have a scenario written in English, but play in German. In the journal I have a link for a dodge check that looks like this:
`@coc7.check[type:skill,name:dodge]`

The skill "Dodge" is called "Ausweichen" in German. And therefore the corresponding skill is not found in the actors.

However, if it were possible to enter the CoC Id in the link, it would work, regardless of what the skill is called in the localization.

In this case, the link would look something like this:
`@coc7.check[type:skill,id:i.skill.dodge]`

I think this would promote localization and acceptance of the system.

**Comment by snap01** [comment]
You can use the CoC ID as name ```@coc7.check[type:skill,name:i.skill.dodge]``` currently you have to use ```@coc7.check[type:skill,name:i.skill.dodge]{Dodge check}``` but in the next release it will automatically search for and populate the name on the links
