### ISSUE TITLE
Actor Importer - Missing Stats on import

### ISSUE THREAD

**Issue by MNight75** [HavlockV/CoC7-FoundryVTT#1550]
Actor Importer Not bringing in Stats for STR DEX etc

Running latest Foundry 12 Stable 235
Running latest COC7th 0.10.14

I open Actor Importer and paste in a properly formatted actors stats, set to NPC, No convert. 
Everything comes in fine except base Stats. 
Even the Example given, copied into the box results in same issue.

**Comment by MNight75** [comment]
Is the absence of the module folder in the directory for the system usual?
I looked for module/apps/actor-importer.js and could not find the
directory, any of its subfolders nor the js that was cited.

**Comment by snap01** [comment]
The code is compiled into the single file bundle.js.
If you want to try compiling the system yourself some information can be found here https://github.com/Miskatonic-Investigative-Society/CoC7-FoundryVTT/blob/develop/.github/CONTRIBUTING.md
