### ISSUE TITLE
Altered Rolls with bonus die / dice are not working with "Dice so Nice" module

### ISSUE THREAD

**Issue by OWL-Fashioned** [HavlockV/CoC7-FoundryVTT#1583]
### Prerequisites.

- [x] Have you checked the Upcoming Release section of the changelog to see if the issue will be resolved in the next release? https://github.com/Miskatonic-Investigative-Society/CoC7-FoundryVTT/blob/develop/.github/CHANGELOG.md
- [x] Are you running the latest version of both Foundry VTT and Call of Cthulhu 7th Edition?
- [x] Have you tested whether the bug persists without any other modules activated or on Foundry Launch in Safe Configuration?

## Browser and OS

Chrome / Firefix / Edge, Windows 10

## Description.

FVTT version: 12.330

Dice so Nice version: 5.0.5 

Call of Cthulhu 7th Edition Version: 0.10.19

Whenever a player tries to roll an altered skill check with a bonus die /dice the result isn't showing up (neither are the 3D dice). It appears in chat after the application / website has been reloaded. Strangely the penalty dice are working fine. I added the error message here as well.

`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'material') at DiceFactory.generateMaterialData (main.js:6:756993) at DiceFactory.create (main.js:6:746744) at async DiceBox.spawnDice (main.js:16:186431) at async DiceBox.rollDice (main.js:16:194061) at async DiceBox.start_throw (main.js:16:191414) at async main.js:16:228566`

## Expected Behavior.

The altered skill check should be rolled and shown in the chatlog.

## Actual Behavior.

Neither the die / dice roll nor the chat message is shown.

**Comment by snap01** [comment]
This is an issue with the bronze dice, as a temporary fix for this under settings for "Call of Cthulhu 7th Edition" under the "Dice So Nice Settings" change bronze to bronze01

**Comment by OWL-Fashioned** [comment]
Thank you so much! Now all the checks work flawlessly again.
