### ISSUE TITLE
Ranged Weapons (such as Bow & Arrow) do not add DB damage even if set

### ISSUE THREAD

**Issue by GambetTV** [HavlockV/CoC7-FoundryVTT#1600]
If a weapon is set to be a Ranged Weapon, it will not add +DB or +DB/2 even if these are set. So for weapons like the Bow and Arrow, which does 1d6 + half DB, it only adds the 1d6 damage, but does not add the +DB/2. Changing the bow and arrow to a melee weapon works, but obviously changes the nature of the weapon in a variety of other ways.

Note: this only applies when rolling via the combat card, attacking first, and then rolling damage. If you only roll damage, then it seems to work properly.

**Comment by lozanoje** [comment]
Tested also with latest Foundry/CoC and same results, combat flow with chat cards does not rolls db/2

**Comment by TravisDean** [comment]
Can confirm as well.
