### ISSUE TITLE
Character Sheet Broken in CoC 7.0

### ISSUE THREAD

**Issue by cornyB23** [HavlockV/CoC7-FoundryVTT#1607]
Character Sheets broken with CoC 7.0 (Foundry v11)

### Prerequisites.

- [ x] Have you checked the Upcoming Release section of the changelog to see if the issue will be resolved in the next release? https://github.com/Miskatonic-Investigative-Society/CoC7-FoundryVTT/blob/develop/.github/CHANGELOG.md
- [ ] Are you running the latest version of both Foundry VTT and Call of Cthulhu 7th Edition?
- [x ] Have you tested whether the bug persists without any other modules activated or on Foundry Launch in Safe Configuration?

## Browser and OS
Chrome, Windows 10

## Description.

The character sheet no longer displays correctly. Just shows a list of skills and inventory items

## Expected Behavior.

The character sheet should display as before

## Actual Behavior.

It doesn't

## Screenshots.

![broken character sheet](https://github.com/user-attachments/assets/f08849d8-9057-4a08-81aa-6b87dc933ac5)

**Comment by sdrew145** [comment]
![CoCBug](https://github.com/user-attachments/assets/96121a90-0028-4bf4-a6a9-531824feb8e1)
Exact same issue, all was working fine, I updated to v7.0 and all the character sheets are now broken. Also th GM tools are missing, I can't import characters or do skill updates etc.

And we were just about to start Children of Fear as well :-)
