### ISSUE TITLE
Cannot read properties of undefined (reading 'CoCIDFlag')

### ISSUE THREAD

**Issue by Haaffin** [HavlockV/CoC7-FoundryVTT#1627]
Whenever I try to do anything that seemingly uses the ID system, nothing happens and I get an error in the console (screenshot of error added below)

### Prerequisites.

- [X] Have you checked the Upcoming Release section of the changelog to see if the issue will be resolved in the next release? https://github.com/Miskatonic-Investigative-Society/CoC7-FoundryVTT/blob/develop/.github/CHANGELOG.md
- [X] Are you running the latest version of both Foundry VTT and Call of Cthulhu 7th Edition?
- [x] Have you tested whether the bug persists without any other modules activated or on Foundry Launch in Safe Configuration?

## Browser and OS

Server is running on Ubuntu 24.04.1 and I'm accessing it from Opera GX on Windows 10

## Description.

It happens when I try to go past the step of the investigator wizard where you choose your name, residence, etc, and also when I try to change/set the ID of an item.

## Expected Behavior.

To be able to create an investigator through the wizard, and set the ID of skills

## Actual Behavior.

Nothing happens and I get error below in the developer console

## Screenshots.

![image](https://github.com/user-attachments/assets/267ab7ee-83a4-4786-be2a-ee2f652dcebe)

## Possible Fix.

Unknown

**Comment by snap01** [comment]
Hello, Do you still get errors if you disable all modules?

**Comment by Haaffin** [comment]
> Hello, Do you still get errors if you disable all modules?

I do, yeah. Tried if first with my modules enabled, then I tried it both disabled, and in a fresh new world as well

**Comment by Haaffin** [comment]
I discovered the cause. It appears to have something to do with incompatibility with [Prettier Login Screen](https://github.com/dandln/Foundry-VTT-Prettier-Login-Screen). Forgot I had that enabled on my server. As soon as i changed the server language from the Prettier Login Screen option, to english, it started working

**Comment by snap01** [comment]
Thank you for the update, we've now been able to replicate the issue. As a temporary solution you could add Latin as a translated language in the system.json file and point it to en.json like this.
```
    {
      "lang": "la",
      "name": "Latin",
      "path": "lang/en.json"
    }
