### ISSUE TITLE
Character Sheet Additions

### ISSUE THREAD

**Issue by Ghrimvold** [HavlockV/CoC7-FoundryVTT#1630]
Is there a chance to add details like "Hit Points" "Luck" "Sanity" and "Magic Points" to the maximized version of the Character Sheet?

**Comment by snap01** [comment]
On the scene controls on the left hand side under the Keeper's tool submenu you need to toggle off Development phase and Character creation mode

**Comment by Ghrimvold** [comment]
...derp...

Thank you :)
