### ISSUE TITLE
Manual adding sources of insanity and and immunities don't work properly

### ISSUE THREAD

**Issue by theczarek** [HavlockV/CoC7-FoundryVTT#1635]
### Prerequisites.

- [ V] Have you checked the Upcoming Release section of the changelog to see if the issue will be resolved in the next release? https://github.com/Miskatonic-Investigative-Society/CoC7-FoundryVTT/blob/develop/.github/CHANGELOG.md
- [ V] Are you running the latest version of both Foundry VTT and Call of Cthulhu 7th Edition?
- [ V] Have you tested whether the bug persists without any other modules activated or on Foundry Launch in Safe Configuration?

## Browser and OS

Win10, Chrome 131.0.6778.86

New Item is not addet to the list when using button and form on screenshot below
(to be precise - I'm clicking "Dodaj" ("add") not "cancel".)
Bug occurs for both options - Sources and Immunities
## Expected Behavior.

New Items should be added
## Actual Behavior.

Nothing
## Screenshots.

![image](https://github.com/user-attachments/assets/94a84f14-82a9-4746-a854-939cc2d94bfd)
![Błąd](https://github.com/user-attachments/assets/0e1568ba-154d-4d80-8543-5693976418b7)

**Comment by snap01** [comment]
Fixed with #1636 and will be included in a future release
