### ISSUE TITLE
No Easy Way to Aquire Selected dt Die from Chat Message

### ISSUE THREAD

**Issue by jacobwojoski** [HavlockV/CoC7-FoundryVTT#1638]
I'm the developer of the Dice Stats module and had a request to add a way to handle CoC dt + d10 rolls as d100. 

This requires me pulling the data from the chat message after its been completed. The problem is there's no way 
for me to tell what dt die is used in the result if there are multiple without dealing with parsing of the raw html content.

I would love a way to see what dt die is used in the final result. I'd recommend adding an isSelected field in the roll dice output or turning the roll formula into a #dtkh or #dtkl. EX: 4dtkh vs 1dt + 1dt + 1dt + 1dt formula.  
Or just have a space in the chat data where the actual final result is saved. 

Where to add the potential isSelected field and the formula that doesnt let me see what die is selected. 
additional the resulting outcome would be nice (Failure, Success, Crit, etc..)
![image](https://github.com/user-attachments/assets/a4088b27-ee55-4b8d-9412-779d91e5f4fd)

**Comment by snap01** [comment]
Unfortunately kh/dh do not work if the units result is 10 and the tens result could also be 10. Also if the user is using Dice So Nice, tens dice after the first can have a different skin.

The check function now alters the Roll, updating each result to indicate active, and total, in your example it would be
Roll.0.dice.0.results.0.active = boolean
Roll.0.dice.0.results.1.active = boolean
Roll.0.dice.0.results.2.active = boolean
Roll.0.total = integer
Roll.0.options.coc7Result.successLevel = enum (fumble, failure, regular, hard, extreme, or critical)
Roll.0.options.coc7Result.difficultySet = boolean (if this is false the difficulty has not been set yet, so it is unknown if the successLevel passed the requirement, i.e. You need to roll extreme success but only rolled a hard)
Roll.0.options.coc7Result.passed = boolen (was the roll an equal or greater success level than required)

**Comment by JornieNonsubia** [comment]
@snap01 Hello, can we also get a isPushed boolean?

**Comment by jacobwojoski** [comment]
Looks great! Thanks!

**Comment by snap01** [comment]
Roll.0.options.coc7Result.pushing = boolean, if true this is the old message
Roll.0.options.coc7Result.pushed = boolean, if true this message it the pushed message
Roll.0.options.coc7Result.luckSpent = int, the amount of luck spent
