### ISSUE TITLE
Damage not applied from Extreme Success when using shotguns

### ISSUE THREAD

**Issue by andy-jones** [HavlockV/CoC7-FoundryVTT#1646]
When scoring a critical or extreme success firing a shotgun, it calculates and displays the damage correctly, but when you click "Inflict Pain" it inflicts 0 damage instead. 

### Prerequisites.

- [Y ] Have you checked the Upcoming Release section of the changelog to see if the issue will be resolved in the next release? https://github.com/Miskatonic-Investigative-Society/CoC7-FoundryVTT/blob/develop/.github/CHANGELOG.md
- [Y ] Are you running the latest version of both Foundry VTT and Call of Cthulhu 7th Edition?
- [Y ] Have you tested whether the bug persists without any other modules activated or on Foundry Launch in Safe Configuration?

## Browser and OS

Mac OS X 15.1.1 using the standalone Foundry application
## Description.

When scoring a critical or extreme success firing a shotgun, it calculates and displays the damage correctly, but when you click "Inflict Pain" it inflicts 0 damage to the character instead. This appears to only be the case with shotguns, it seems to work fine with handguns. 

## Expected Behavior.

It should apply the amount of damage it calculated previously, not 0.
## Actual Behavior.

It applies 0 points of damage to the character, even though it calculated and displayed the correct amount of damage previously.
## Screenshots.

![Screen2](https://github.com/user-attachments/assets/3f5c7771-a135-4e96-a7f4-f866b84a93e3)
![Screen3](https://github.com/user-attachments/assets/3922632d-bc89-4bcb-aa53-fc44d192e1e0)

## Possible Fix.

Suspect it might be to do with the different levels of damage at different ranges that applies to shotguns but not handguns?

**Comment by snap01** [comment]
A fix for fixed ranged damage, is in the 7.6 release
