### ISSUE TITLE
Chat card for CON check when wound is immediate death

### ISSUE THREAD

**Issue by lozalojo** [HavlockV/CoC7-FoundryVTT#838]
CoC 0.6.9, Core 0.8.9

## Description.

When aplying a wound higher than HPs of the target, chat card request a CON check . When someone receives a wound equal to his HPs or higher, it dies immediately, no CON check requested.

## Screenshots.

![](https://i.ibb.co/pZXG15s/screenshot-184.jpg)

## Possible Fix.

Do not ask for CON check when result is immediate death.

**Comment by joaovscorreia** [comment]
Gracias!
