### ISSUE TITLE
Allow GM to Edit Name of Spell in Book OR Add a player-facing name to the base spell item object

### ISSUE THREAD

**Issue by claycle** [HavlockV/CoC7-FoundryVTT#900]
## Description of Problem

In the current implementation of spell books, once you drag a spell over to the book, it is "locked" in that the GM can no longer edit the name of the spell. If drawing from an already established library of spell items, the GM must create a duplicate of the original spell item, drag the duplicate over, and then delete the duplicate from the item library (since it is only needed to obscure the actual spell/grant flavor in the spell book that the player manipulates.

## Feature Request 

It would be great to short-cut this some how, by one of the following methods:

1. Create a "player-facing name" on the base spell item, so that this problem is solved in all cases. As this is something very commonly done in actual play (and in fact encouraged by RAW), it seems the ideal solution. Players would only see the player-facing name of the spell object, whereas the GM would see both the player-facing name and the actual name of the spell (which likely derives from the spell item library they have created in Foundry); or
2. Allow the GM to create a player-facing name for the spell per spell book. The player-facing spell name exists only as line item related to the spell item dropped into the spell book item by the GM; or
3. Allow the GM to edit the name of the copy of the spell item attached to the spell book item.

**Comment by joaovscorreia** [comment]
Hey, @claycle, this feature is under development on #887

**Comment by claycle** [comment]
Perhaps just change this feature request to provide for the player-facing name on the base spell object then to solve a more general (and larger) case?
