### ISSUE TITLE
Error messages when updating a world with locked compendiums

### ISSUE THREAD

**Issue by vonv** [HavlockV/CoC7-FoundryVTT#908]
![Foundry Virtual Tabletop • A Standalone Virtual Tabletop Application — Mozilla Firefox](https://user-images.githubusercontent.com/44206935/138459480-60b133fe-b165-42b2-88c2-e40e0991f886.jpg)

**Comment by joaovscorreia** [comment]
@vonv are you having this issue even running the 0.7.1 version?

**Comment by vonv** [comment]
Yeap. From 0.6.X to 0.7.0 and 0.7.0 to 0.7.1.

**Comment by vonv** [comment]
With my own compendiums.

**Comment by vonv** [comment]
To be precise, it's for items compendiums.

**Comment by snap01** [comment]
@vonv the updater should unlock each compendium before attempting to update it, are the files marked read only by the operating system or do you have a module that prevents the compendiums from being unlocked?

**Comment by vonv** [comment]
Last update OK!
