### ISSUE TITLE
Not function about Reveal check

### ISSUE THREAD

**Issue by zeteticl** [HavlockV/CoC7-FoundryVTT#909]
- [x] Are you running the latest version of both Foundry VTT and Call of Cthulhu 7th Edition?
- [x] Have you tested whether the bug persists without any other modules activated or on Foundry Launch in Safe Configuration?

## Description.

when i press  Reveal check ， it didnt have any respone

## Screenshots.

![image](https://user-images.githubusercontent.com/23254376/138580394-3bea7e76-86b7-46cf-b027-d6fc3b70d6cc.png)

**Comment by claycle** [comment]
Confirmed. Can reproduce. Nothing appears in the console.
