### ISSUE TITLE
Pulp Luck Rolls bug

### ISSUE THREAD

**Issue by mdrueen** [HavlockV/CoC7-FoundryVTT#923]
The pulp luck replenishes rules, as written, aren't working correctly. 

### Prerequisites.

 

- [ ] Are you running the latest version of both Foundry VTT and Call of Cthulhu 7th Edition?  - yes
- [ ] Have you tested whether the bug persists without any other modules activated or on Foundry Launch in Safe Configuration? N/A

## Description.

A successful (roll luck or below) earns 1d10 + 5. A failed luck roll (above the luck value) should earn 2d10 +10. This isn't what is happening. When someone has pulp rules turned on in the system, the above is what should happen.

## Actual Behavior.

I had  a character earn 25 luck when they rolled below their luck. At most his can only ever be 15 luck points regained.

**Comment by joaovscorreia** [comment]
This was fixed by [c44f31698f3deaab037ecb7a16330f9a62c812ba](https://github.com/Miskatonic-Investigative-Society/CoC7-FoundryVTT/commit/c44f31698f3deaab037ecb7a16330f9a62c812ba), that is not live yet
