### ISSUE TITLE
Change in book reading time values. 

### ISSUE THREAD

**Issue by mdrueen** [HavlockV/CoC7-FoundryVTT#924]
While the core rule book lists "weeks" as the only time measure for reading books, most scenarios deviate from this. So a book can in some adventures take hours, days, weeks or months. Please allow there to be a toggle or something to change "weeks" to hours and days as well. 

## Description.

Add hours and days as an option when creating a book.

**Comment by joaovscorreia** [comment]
Hey, @mdrueen, could you please name which scenarios have these different measures of reading time?
