### ISSUE TITLE
Selective Rest Updating

### ISSUE THREAD

**Issue by Dick-K** [HavlockV/CoC7-FoundryVTT#945]
The Keeper can currently invoke a Keeper's Tools/Start Rest function. This applies an HP increment and Daily Sanity Loss restart to all Actors. The Keeper may not wish all Actors to benefit from this.

## Description.

When the Keeper invokes the Keeper's Tools/Start Rest function, provide a mechanism that allows the Keeper to select which Actors will receive the benefit of resting with a convenient default of "All".

## Rule Source

This is not a rule change or inclusion but a usability feature. There are a variety of reasons why a Keeper may wish to be selective regarding the Actors who should benefit from resting.

## Context.

A specific Actor may be in a situation which, according to the Keeper's judgement, prevents Healing or a Daily Sanity Loss restart even if the Actor rests or the situation for a specific Actor prevents resting altogether. 

## Possible Implementation.

Present a card that displays a list of candidate actors, the keeper can then check the ones that may benefit from resting. Card also presents a button "Apply to All".

**Comment by joaovscorreia** [comment]
Resolved by #946, thank you!
