### ISSUE TITLE
User lacks permissions to update ChatMessage while answering a roll request by GM

### ISSUE THREAD

**Issue by FelixHe** [HavlockV/CoC7-FoundryVTT#947]
### Prerequisites.

- [Y] Are you running the latest version of both Foundry VTT and Call of Cthulhu 7th Edition?
- [Y] Have you tested whether the bug persists without any other modules activated or on Foundry Launch in Safe Configuration?

## Description.

I created actors for my players and assigned them to the users as Owner. Now as a game master I can request a roll from an actor/player if I make a left click onto the skill within the character sheet of the investigators. Then a message is posted to the chat which only the linked player can see. Afterwards he/she can click on the button "Roll" in the chat to do exactly the skill test I as a game master requested from him/her. I can see the dice rolling over the canvas (with the addon DiceSoNice) but the players are always getting the error message: "lacks permission to update ChatMessage" 

## Expected Behavior.

The player should be able to execute the roll and the chat should be updated with the result of the roll.

## Actual Behavior.

The player gets a error message that says: "lacks permission to update ChatMessage"

**Comment by officerzan** [comment]
Can confirm. This also happens on Melee damage rolls, but not ranged damage rolls. The module is assigning the GM, or a random GM in the case of multiple with GM/assistant role, as owner of the message instead of the player.

**Comment by joaovscorreia** [comment]
(Apparently) fixed by #958; if this problem persists, please reopen this Issue. Thank you!
