### ISSUE TITLE
Combined Rolls

### ISSUE THREAD

**Issue by officerzan** [HavlockV/CoC7-FoundryVTT#961]
Combined Rolls (Alt + Right Clicking skills) does not function correctly.

### Prerequisites.

- [x] Are you running the latest version of both Foundry VTT and Call of Cthulhu 7th Edition?
- [x] Have you tested whether the bug persists without any other modules activated or on Foundry Launch in Safe Configuration?

## Description.

Players making Combined Rolls in the module have to do so one at a time because everyone attempting a Combined Roll just gets added to the same card. There is also no way to set individual difficulty levels.

## Expected Behavior.
"Everyone make a Science (Biology or Zoology) or Hard Natural World test."

Each player should be able to add Science (Biology), Science (Zoology), and Natural World to their own card to roll. It should check for regular success on the first two, and hard success on the last.

## Actual Behavior.
"Everyone make a Science (Biology or Zoology) or Hard Natural World test."

All skills checked regardless of selected actor are added to the same card and when rolled can only be set to check a single difficulty.

**Comment by Dick-K** [comment]
May I also add the following to this bug report:
Using Foundry v9.242 (stable) and CoC 7E (Unofficial), the combined roll mechanism does not honour the requested Bonus dice from the Options dialog. E.g. specifying +1 Bonus dice results in a single 10s dice for all participants. The following screenshot shows the single 10s dice rolled when a +1 Bonus dice was requested:

![image](https://user-images.githubusercontent.com/73724728/148694623-c9e94643-579c-486f-90cd-c31633ecd970.png)

**Comment by officerzan** [comment]
Can confirm @Dick-K 's post, Combined Rolls appear to ignore penalty and bonus dice given when rolling in addition to the issues listed previously listed.
