### ISSUE TITLE
cannot add ranged weapons

### ISSUE THREAD

**Issue by flattenstream** [HavlockV/CoC7-FoundryVTT#977]
cannot add ranged weapons

### Prerequisites.

- [x] Are you running the latest version of both Foundry VTT and Call of Cthulhu 7th Edition?
- [x] Have you tested whether the bug persists without any other modules activated or on Foundry Launch in Safe Configuration?

## Description.
Hi. Whenever I click the add button of ranged weapons it just adds melee weapons.

**Comment by joaovscorreia** [comment]
@flattenstream can you please give us more details on how to reproduce this bug?

**Comment by markspace** [comment]
Seeing the same problem:
Core version 9.242 Foundry VTT running on Windows 10
Call of Cthulhu System 0.7.3

Created a new world with the above
Logged in as Gamemaster
Added actor
Added a Brawl skill and a Handgun skill (from the Skills Compendium Pack)
Goto Combat tab
Make sure Actor is unlocked
click + on Ranged Weapon line
a new Melee weapon line appears
clicking on + on Melee weapons also gets a Melee weapon

I can't find a way of adding a Ranged Weapon

**Comment by markspace** [comment]
Workround
Add the weapon as an Item in the Items Directory (eg Handgun - Range) and drag it onto the Actor

**Comment by officerzan** [comment]
@markspace
Clicking the plus button on melee or ranged is just a "create a new blank weapon" button. The Melee/Ranged tags are what determines under which accordion the weapon is placed.

So, first, click the plus to add a weapon (doesn't matter which). Then, click either melee or ranged to tell the system which type of attack/weapon you are creating. You will find that the weapon is placed within the correct accordion that matches the tag.

That said...
## Possible Fix.
When creating a "weapon" from the buttons on the character sheets assign the tag that corresponds to the plus button clicked.
Ie, clicking the **+** by Melee Weapons assigns the melee tag by default while clicking the **+** by Ranged Weapons assigns the Ranged Tag by default.
