### ISSUE TITLE
Dice so Nice showing 2 d10s instead of percentiles. 

### ISSUE THREAD

**Issue by ErroneousBosch** [HavlockV/CoC7-FoundryVTT#978]
Running latest versions of all relevant modules in a new blank game, DsN seems to use 2 d10s rather than proper percentile dice when rolling skills. using `/r 1d%` generates the same result.

**Comment by officerzan** [comment]
I am unable to recreate this issue. I am currently using...
- FVTT v9 (build 242)
- CoC 7e (Unofficial) v0.7.3
- DsN v4.3.1 [also tested with prior v4.2.2]

**Comment by ErroneousBosch** [comment]
Hmm Issue does seem to have resolved itself, probably somewhere in an update chain.

**Comment by joaovscorreia** [comment]
Thanks for the report, @ErroneousBosch
