### ISSUE TITLE
Sanity Check with Min/Max Lacks Feedback and Requires Dbl-Click to Confirm

### ISSUE THREAD

**Issue by Dick-K** [HavlockV/CoC7-FoundryVTT#989]
When generating a Keeper Sanity roll request from a player's sheet using Min/Max Sanity Loss parameters, the dialog lacks feedback when the Min/Max values are not entered and requires a dbl-click to activate once completed correctly.

### Prerequisites.

- [Y] Are you running the latest version of both Foundry VTT and Call of Cthulhu 7th Edition?
- [Y] Have you tested whether the bug persists without any other modules activated or on Foundry Launch in Safe Configuration?

## Description.

If, as Keeper, I open a player's sheet and use Ctrl-Alt-Click on the highlighting Sanity title, I am presented with the following dialog panel:

![image](https://user-images.githubusercontent.com/73724728/150018042-0a182a53-09e5-4dd6-87a2-1b9041bf60e9.png)

The panel has 2 issues:

1) If the Min and Max sanity loss values are not entered, none of the buttons work. There is no feedback such as 'Enter MinMax Values'.
2) Having entered the Min/Max values a dbl-click is required to activate any of the option buttons.

## Expected Behavior.

1) Feedback when panel is not completed correctly.
2) Single click to activate option button.

## Actual Behavior.

1) If the Min and Max sanity loss values are not entered, none of the buttons work. There is no feedback such as 'Enter MinMax Values'.
2) Having entered the Min/Max values a dbl-click is required to activate any of the option buttons.

**Comment by snap01** [comment]
Thanks,

1. We've added some browser required checks.
2. The double click requirement is caused by the link changing and causing the form to refresh. We've added a UI element to show the link so it is clearer something has changed.
