### ISSUE TITLE
Limited Permission Not Applied to Journal Entries

### ISSUE THREAD

**Issue by Dick-K** [HavlockV/CoC7-FoundryVTT#995]
Setting a Journal Entry to Limited for a player no longer places an entry in the player's journal tab.
### Prerequisites.

- [Y] Are you running the latest version of both Foundry VTT and Call of Cthulhu 7th Edition?
- [Y] Have you tested whether the bug persists without any other modules activated or on Foundry Launch in Safe Configuration?

## Description.

In a prior version of either Foundry or the CoC sheet (I'm not sure which), setting a Journal Entry to _Limited_ for a player would place an entry for that journal in the player's journal tab, allowing to to view just the _Image_ component.

With the latest version of Foundry and the CoC7E system, no entry is placed in the player's journal tab.

## Expected Behavior.

An entry should be placed in the player's journal tab allowing them to view the _Image_ component of the Journal Entry.

## Actual Behavior.

Setting a Journal Entry to Limited for a player does nothing, no entry is placed in their journal tab.

Tested without modules.

**Comment by snap01** [comment]
This behaviour is controlled by FoundryVTT, the visible function in the class JournalEntry requires observer permissions to see an entry in the list.

The JournalEntry system is getting an upgrade for v10 which currently does allow you to set different permissions per page.
