### ISSUE TITLE
NPC Temporary and Indefinite Insanity Flags May Not Be Unchecked

### ISSUE THREAD

**Issue by Dick-K** [HavlockV/CoC7-FoundryVTT#997]
If an NPC's or Monster's Insanity is changed such that the Temporary and Indefinite Insanity flags are checked, they cannot be unchecked even if the Sanity value is restored.

### Prerequisites.

- [Y] Are you running the latest version of both Foundry VTT and Call of Cthulhu 7th Edition?
- [Y] Have you tested whether the bug persists without any other modules activated or on Foundry Launch in Safe Configuration?

## Description.
If an NPC's or Monster's Insanity is changed such that the Temporary and Indefinite Insanity flags are checked, they cannot be unchecked even if the Sanity value is restored.

E.g. As GM, open an NPC or Monster Actor sheet which have their original unchanged Sanity values. Overwrite the current Sanity value so that the Temporary and Indefinite sanity flags are checked in red. Restore the current Sanity value to its original value. Note that the Temporary and Indefinite sanity flags remain checked in red and cannot be unchecked.

## Expected Behavior.

GM should be able to uncheck the Temporary and Indefinite sanity flags.

## Actual Behavior.

Temporary and Indefinite sanity flags may not be unchecked by the GM.

**Comment by snap01** [comment]
Thanks for the report, #981 changes many parts of the Temporary and Indefinite Insanity flags including allowing them to be toggled on and off.
